---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by larryhou.
--- DateTime: 2018/9/1 1:35 PM
---

level = 8

function check_available(list, r, c)
    for i = 1, r - 1 do
        if list[i] == c
                or list[i] - c == i - r
                or list[i] - c == r - i then
            return false
        end
    end
    return true
end

function dump_solution(solution)
    --result = ""
    --for r = 1, level do
    --    result = result .. string.format("{%d,%d}", r, solution[r])
    --end
    --print(result)

    for r = 1, level do
        for c = 1, level do
            io.write(solution[r] == c and "o" or "-")
            io.write(" ")
        end
        io.write("\n")
    end
    io.write("\n")
end

function find_solution(solution, r)
    if r > level then
        dump_solution(solution)
    else
        for c = 1, level do
            if check_available(solution, r, c) then
                solution[r] = c
                find_solution(solution, r + 1)
            end
        end
    end
end

find_solution({}, 1)

table.concat()