---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by larryhou.
--- DateTime: 2018/9/3 3:11 PM
---


function insert(s, offset, data)
    l = string.sub(s, 1, offset - 1)
    r = string.sub(s, offset, -1)
    result = l .. data .. r
    print(result)
    return result
end

function insert_utf(s, offset, data)
    l = string.sub(s, 1, utf8.offset(s, offset)-1)
    r = string.sub(s, utf8.offset(s, offset), -1)
    result = l .. data .. r
    print(result)
    return result
end

function remove(s, offset, length)
    l = string.sub(s, 1, offset - 1)
    r = string.sub(s, offset + length, -1)
    result = l .. r
    print(result)
    return result
end

function remove_utf(s, offset, length)
    l = string.sub(s, 1, utf8.offset(s, offset) - 1)
    r = string.sub(s, utf8.offset(s, offset + length), -1)
    result = l .. r
    print(result)
    return result
end

function print_table(t, depth)
    index = #t + 1
    t[index] = math.random()
    print(t, #t)
    if depth <= 5 then
        print_table(t, depth + 1)
    end
end

insert('hello world', 1, 'start: ')
insert('hello world', 7, 'small ')
insert_utf('我叫侯沐白我最棒', 5, "!")

remove('hello world', 7, 4)
remove_utf('我叫侯沐白我最棒', 2, 2)

print_table({}, 1)